### ISSUE TITLE
Week of 10-14

### ISSUE THREAD

**Issue by Dragon0344** [domph/p1-rain#18]
- [ ]  Actually fix the commenting code(integrate buttons and image upload
- [ ] Play with a few other functions if possible
- [ ] Finish the minilabs and link them
[https://github.com/domph/p1-rain/commit/aa839eed048191e118209f6bb4a5e48c1259d50d](url)

**Comment by AndrewPhilipJoseph** [comment]
What do you mean by fixing the commenting code and "play with a few other functions"? Other than that confusion, nice work.

**Comment by domph** [comment]
Agree with @AndrewPhilipJoseph on the vagueness of fixing commenting code and playing w/ a few functions. The upload test showcases a different way of loading/displaying images, which is neat! It's a bit hard to evaluate though since it's not directly accessible from the website (need to run from IntelliJ).

**Comment by banditcat12** [comment]
this ticket does not make clear what you are doing at all. and I don't think playing with functions should constitute a step. The commit is only about a hundred lines of sparsely populated HTML/CSS code
